dspsrc  := $(wildcard *.dsp)
cppsrc  := $(addprefix $(DEST), $(dspsrc:.dsp=.cpp))
appl 	:= $(addprefix $(DEST), $(dspsrc:.dsp=$(EXT)))


all :  $(appl)

ifdef ARCH
include_arch := -a $(ARCH)
endif

$(DEST)%$(EXT) : %.dsp 
	faust $(VEC) $(include_arch) $< -o $@.cpp
	$(CXX) $@.cpp $(CXXFLAGS) $(LIB) -o $@
	

clean :
	rm -f $(DEST)
